apiVersion: v2
name: auto-ns-opentelemetry-instrumentation
description: Operator to apply instrumentation into namespaces labeled apm-observe=true
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/SevginGalibov/auto-ns-opentelemetry-instrumentation
sources:

  - https://github.com/SevginGalibov/auto-ns-opentelemetry-instrumentation
maintainers:
  - name: SevginGalibov
    email: sevgin@example.com

