apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auto-ns-opentelemetry-instrumentation-binding
subjects:
  - kind: ServiceAccount
    name: auto-ns-opentelemetry-instrumentation
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: auto-ns-opentelemetry-instrumentation
  apiGroup: rbac.authorization.k8s.io
