apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auto-ns-opentelemetry-instrumentation
rules:
  - apiGroups: [""]
    resources: ["namespaces", "configmaps", "pods", "services", "serviceaccounts"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["opentelemetry.io"]
    resources: ["instrumentations"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
